server:
  port: 8091
# Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
# Specify the path of the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
# Enable or disable Swagger UI
    enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/lux_basicdatabase
    username: root
    password: lakmali
    driver-class-name: com.mysql.jdbc.Driver